version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
      - run: yarn --frozen-lockfile
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 14.3.0
                - 12.17.0
                - 10.20.0
