version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  test:
    docker:
      - image: node:<< parameters.main-version >>
    parameters:
      main-version:
        default: 12
        type: integer
    steps:
      - checkout
      - restore_cache:
          name: 'Restoring cache'
          key: bestrunner-<<parameters.main-version>>-{{ checksum "yarn.lock" }}
      - run:
          name: 'Install packages'
          command: yarn install --frozen-lockfile
      - save_cache:
          name: 'Saving cache'
          key: bestrunner-<<parameters.main-version>>-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - modules/eslint-config-bestrunner/node_modules
            - modules/runner/node_modules
            - modules/suite/node_modules
      - run:
          command: yarn test
          name: Run YARN tests
      - store_test_results:
          path: test-results

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              main-version:
                - 14
                - 12
                - 10
