#!/bin/bash
for v in 10 12 14;
do
	latest=`npx n ls-remote --all | ag "^$v" | head -n 1`
	sed -i "s/- $v.*/- $latest/" .circleci/config.yml
done

diff=`git diff-files | ag .circleci/config.yml`

if [[ -n "$diff" ]]; then
	git checkout -b upgrade-node-versions
	git add .circleci/config.yml
	git commit -m "chore: set latest versions of node in circleci"
	git push origin upgrade-node-versions
	hub pull-request --no-edit
fi
